### ISSUE TITLE
0.1.0 doesn't creat database when api server start

### ISSUE THREAD

**Issue by ReigenAraka** [zilliztech/phantoscope#101]
**Describe the bug**
api server not creat database correctly

**Steps/Code to reproduce behavior**

**Expected behavior**

**Environment details**
- Phantoscope version (v0.1.0)
- wsl 2.0

**Screenshots**

**Additional context**

**Comment by ReigenAraka** [comment]
#120

**Comment by ijackwu** [comment]
try agent
```bash

git checkout 0.1.0

rm /mnt/om

```

**Comment by ABNER-1** [comment]
It is usually caused by run scripts quickly when docker-compose ok. 
Wait for some seconds or restart docker-compose container maybe help.
Close this issue.
