### ISSUE TITLE
Two problems under MacOS

### ISSUE THREAD

**Issue by guoxiangzhou** [zilliztech/phantoscope#130]
**Describe the bug**
- need to run the command[‘docker-compose up -d’] twice，table of mysql can be created successfully。
- upload images error：ERROR:root:Upload file 'xxx.jpg' error due to: name 'upload_url' is not defined。Becuase multiprocessing on Macos cannot access ‘upload_url’ in load_data.py

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Environment details**
- Docker info
- Phantoscope version (v0.1.0)

**Screenshots**

**Additional context**

**Comment by ReigenAraka** [comment]
Phantoscope is only validated on Ubuntu and CentOS. There may be an incompatibility issue between Windows and MacOS.

**Comment by ABNER-1** [comment]
The first issue is same as #102 
The second issue maybe cause by other version of python or some platform setting.
I will changes the load_data script to fix it.
Thanks for your issue to point out this.

**Comment by ABNER-1** [comment]
Close this issue due to all issues had been traced or fixed.
