### ISSUE TITLE
prepare.sh  return error

### ISSUE THREAD

**Issue by yAnG12121** [zilliztech/phantoscope#136]
设置环境变量
export LOCAL_ADDRESS=$(ip a | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1'| head -n 1)

Phantoscope 正在运行:
phantoscope_api_1      /usr/bin/gunicorn3 -w 4 -b ...   Up      0.0.0.0:5000->5000/tcp
phantoscope_milvus_1   /var/lib/milvus/docker-ent ...   Up      0.0.0.0:19530->19530/tcp, 0.0.0.0:8080->8080/tcp
phantoscope_minio_1    /usr/bin/docker-entrypoint ...   Up      0.0.0.0:9000->9000/tcp
phantoscope_mongo_1    docker-entrypoint.sh mongod      Up      0.0.0.0:27017->27017/tcp
phantoscope_mysql_1    docker-entrypoint.sh mysqld      Up      0.0.0.0:3306->3306/tcp
phantoscope_vgg_1      python3 server.py                Up      0.0.0.0:50001->50001/tcp

运行 scripts 文件夹下的 prepare.sh 脚本 出现错误
./scripts/prepare.sh
{"message": "opeartor vgg16 regist error", "error": "OperatorRegistError"}{"message": "operator vgg16 not exist", "error": "NotExistError"}{"message": "pipeline not exist", "error": "NotExistError"}

ERROR in operators.operator 103: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses"

**Comment by ReigenAraka** [comment]
make sure set environment successful;
use `env | grep LOCAL_ADDRESS`

**Comment by ABNER-1** [comment]
Please checkout 0.1.0 and read 0.1.0 docs.
Master branch has changed milvus version.

delete all resources by those command:
```shell
docker-compose down
rm -rf /mnt/om
```

**Comment by yAnG12121** [comment]
现在切换到 0.1.0  
phantoscope_api_1      /usr/bin/gunicorn3 -w 4 -b ...   Up      0.0.0.0:5000->5000/tcp
phantoscope_milvus_1   /var/lib/milvus/docker-ent ...   Up      0.0.0.0:19121->19121/tcp, 0.0.0.0:19530->19530/tcp
phantoscope_minio_1    /usr/bin/docker-entrypoint ...   Up      0.0.0.0:9000->9000/tcp
phantoscope_mysql_1    docker-entrypoint.sh mysqld      Up      0.0.0.0:3306->3306/tcp
phantoscope_vgg_1      python3 server.py                Up      0.0.0.0:50001->50001/tcp

执行 prepare.sh  
{"message": "opeartor vgg16 regist error", "error": "OperatorRegistError"}{"message": "query from sql error", "error": "QueryFromSQLError"}{"message": "query from sql error", "error": "QueryFromSQLError"}
phantoscope_api  日志
(MySQLdb._exceptions.OperationalError) (2003, "Can't connect to MySQL server on 'mysql' (111)")
(Background on this error at: http://sqlalche.me/e/e3q8)
count 1; retry to connect to database mysql://root:passwd@mysql:3306/search
 ERROR in operators.operator 103: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses"
没有创建数据库

**Comment by ABNER-1** [comment]
Hello, @yAnG12121 
It is same as #120. You can get help form there.
Did you run `prepare.sh` quickly after `docker-compose up -d`?
Maybe database hasn't been created.

**Comment by yAnG12121** [comment]
感谢您的回复 ，mysql的问题解决了。
启动后执行prepare.sh  也是报这个异常
{"message": "opeartor vgg16 regist error", "error": "OperatorRegistError"}{"message": "operator vgg16 not exist", "error": "NotExistError"}{"message": "pipeline not exist", "error": "NotExistError"}

api log
ERROR in operators.operator 103: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses"
 ERROR in operators.operator 137: ('operator vgg16 not exist', '')

可能是我执行export 命令有问题 ，我快速入门重新配置一下

**Comment by ABNER-1** [comment]
Did you succeed to run quick start？ If ok，I will close this issue.
