### ISSUE TITLE
Can't Run load_data.py

### ISSUE THREAD

**Issue by arya0812** [zilliztech/phantoscope#138]
## Can't Run load_data.py

**Location of incorrect documentation**
[Upload Image Package](https://github.com/zilliztech/phantoscope/tree/0.1.0/docs/site/en/quickstart#upload-image-package)

**Describe the problems or issues found in the documentation**
![Screenshot from 2020-07-08 14-31-40](https://user-images.githubusercontent.com/22544815/86885496-f6663480-c127-11ea-942f-fbfcdc232b9c.png)

**Comment by Adarsh1999** [comment]
Whats the solution to this prob?
