### ISSUE TITLE
when will 0.2 releases?

### ISSUE THREAD

**Issue by ijackwu** [zilliztech/phantoscope#142]

**Comment by ABNER-1** [comment]
Thanks for paying attention to Phantoscope. All features about 0.2.0 have been developed. 
We have already prepared docs about api changes and feature introduction in Chinese version, but new preview front-page supporting and docs in English remains not ok. 
Look forward to the release of the new version, which should be an easier-to-use and more powerful version.

**Comment by ijackwu** [comment]
thinks!
