### ISSUE TITLE
curl: (52) Empty reply from server

### ISSUE THREAD

**Issue by vacher** [zilliztech/phantoscope#153]
**phantoscope 0.2.0**

root@dssy-milvus:/home/phantoscope# **./scripts/prepare.sh**

Register operators named vgg16
{"name": "vgg_encoder", "addr": "psoperator/vgg16-encoder:latest", "author": "ph                                                                                                                                                             antoscope", "version": "0.1.0", "type": "encoder", "description": "vgg16 encoder                                                                                                                                                             ", "runtime_client": "docker", "metadata": {"id": "94f0aa47-ede5-4d07-aeef-c78cd                                                                                                                                                             8c4fbe0", "create_time": "2020-07-28 06:20:44.427142", "resource_type": "Operato                                                                                                                                                             r", "state": "created"}}\n
create operator instance
**curl: (52) Empty reply from server**
\nsleep 10s for instance warmup
Create pipeline with created instance vgg16
{"message": "**No such container: phantoscope_vgg_encoder_vgg_instance1**", "error":                                                                                                                                                              "DockerRuntimeError"}\nCreate application with the created pipeline before
{"message": "pipeline example_pipeline not exist", "error": "ArgsCheckError"}

**Comment by ABNER-1** [comment]
Hello, @vacher. This is an unexpected error.
Please paste the result of these next command.
```bash
docker-compose ps
docker images
docker ps -a | grep phantoscope
docker logs phantoscope_api_1
```

**Comment by vacher** [comment]
**docker-compose ps**
------------------------------------------------------------------------------------------------------------------
phantoscope_api_1      /usr/bin/gunicorn3 -w 4 -b ...   Up      0.0.0.0:5000->5000/tcp
phantoscope_milvus_1   /var/lib/milvus/docker-ent ...   Up      0.0.0.0:19121->19121/tcp, 0.0.0.0:19530->19530/tcp
phantoscope_minio_1    /usr/bin/docker-entrypoint ...   Up      0.0.0.0:9000->9000/tcp
phantoscope_mongo_1    docker-entrypoint.sh mongod      Up      0.0.0.0:27017->27017/tcp

**docker images**
---------------------------------------------------------------------------------------------------------------------
EPOSITORY               TAG                         IMAGE ID            CREATED             SIZE
minio/minio              latest                      cfc7435b60c3        13 hours ago        62.7MB
mongo                    latest                      dee5b549543c        3 days ago          388MB
phantoscope/api-server   v0.2.0                      61df1fbf261c        5 days ago          684MB
milvusdb/milvus          0.10.0-cpu-d061620-5f3c00   bc7ecb203f01        6 weeks ago         400MB

**docker ps -a | grep phantoscope**
--------------------------------------------------------------------------------------------------------------------------
2155b5d023ad        phantoscope/api-server:v0.2.0               "/usr/bin/gunicorn3 …"   4 minutes ago       Up 4 minutes        0.0.0.0:5000->5000/tcp                               phantoscope_api_1
842e6d3afa5d        milvusdb/milvus:0.10.0-cpu-d061620-5f3c00   "/var/lib/milvus/doc…"   4 minutes ago       Up 4 minutes        0.0.0.0:19121->19121/tcp, 0.0.0.0:19530->19530/tcp   phantoscope_milvus_1
62e35d0cbdad        minio/minio:latest                          "/usr/bin/docker-ent…"   4 minutes ago       Up 4 minutes        0.0.0.0:9000->9000/tcp                               phantoscope_minio_1
2c1f18df6b75        mongo                                       "docker-entrypoint.s…"   4 minutes ago       Up 4 minutes        0.0.0.0:27017->27017/tcp                             phantoscope_mongo_1

**docker logs phantoscope_api_1**
-----------------------------------------------------------------------------------------------------------------------------
[2020-07-28 08:54:48 +0000] [1] [INFO] Starting gunicorn 19.7.1
[2020-07-28 08:54:48 +0000] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
[2020-07-28 08:54:48 +0000] [1] [INFO] Using worker: sync
[2020-07-28 08:54:48 +0000] [8] [INFO] Booting worker with pid: 8
[2020-07-28 08:54:48 +0000] [9] [INFO] Booting worker with pid: 9
[2020-07-28 08:54:48 +0000] [10] [INFO] Booting worker with pid: 10
[2020-07-28 08:54:48 +0000] [11] [INFO] Booting worker with pid: 11
[2020-07-28 08:56:39 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:10)
[2020-07-28 08:56:39 +0000] [10] [INFO] Worker exiting (pid: 10)
[2020-07-28 08:56:39 +0000] [42] [INFO] Booting worker with pid: 42
[2020-07-28 08:56:49,510] ERROR in pipeline.pipeline 93: ('No such container: phantoscope_vgg_encoder_vgg_instance1', NotFound(HTTPError('404 Client Error: Not Found for url: http+docker://localhost/v1.35/containers/phantoscope_vgg_encoder_vgg_instance1/json',),))

**Comment by ABNER-1** [comment]
It seems that phantoscope hasn't pull vgg image when create vgg instance.
There are two solutions:
1. pull image by yourself `docker pull psoperator/vgg16-encoder:latest` 
2. create instance by curl until phantoscope pull images successfully.

Maybe the first can quickly help you solve this problem. Then, rerun the script again.

**Comment by vacher** [comment]
success ! it's OK.
Thank you!
