### ISSUE TITLE
post '/v1/operator/ssd_detector/instances/ssd_instance1'  curl: (52) Empty reply from server  

### ISSUE THREAD

**Issue by sunyun0090** [zilliztech/phantoscope#155]
![e3ecf8b729f7b32a7ceb2b45b144da5](https://user-images.githubusercontent.com/14146919/90846910-db7c1680-e39b-11ea-80ab-4fdb11cf6445.png)
![c6784a757b79c1870ce278b2bd99e62](https://user-images.githubusercontent.com/14146919/90847118-59402200-e39c-11ea-96ec-1fce00ad3b2c.png)
![67f5620a871bb896fc08edc45c5aa17](https://user-images.githubusercontent.com/14146919/90847258-b63bd800-e39c-11ea-8718-b67b913c3978.png)

As shown above, i register operator successfully,  instance  creation failure.

**Comment by ABNER-1** [comment]
The same as issuse #153. This happens due to gfw pulling speed from docker hub. You can pull image by yourself or use some proxy to speed up.

**Comment by sunyun0090** [comment]
thanks
