### ISSUE TITLE
Created a container, but did not create an application

### ISSUE THREAD

**Issue by wq1315** [zilliztech/phantoscope#156]
**Describe the bug**
When I use this to create an application, there is no return value, but it has been created when I look at the milvus container

**Expected behavior**
`curl --location --request POST 'localhost:8181/v1/application/example_app' \
--header 'Content-Type: application/json' \
--data '{
    "fields":{
        "example_field": {
            "type": "pipeline",
            "value": "example_pipeline"
        }
    },
    "s3Bucket": "object-s3"
}'`
`(base) [root@localhost phantoscope]# curl --location --request POST 'localhost:8181/v1/application/example_app' \
--header 'Content-Type: application/json' \
--data '{
   "fields":{
       "example_field": {
            "type": "pipeline",
            "value": "example_pipeline"
        }
    },
    "s3Bucket": "object-s3"
}'`

`Traceback (most recent call last):
  File "/app/application/application.py", line 86, in new_application
    MongoIns.new_mongo_collection(f"{app_name}_entity")
  File "/app/storage/storage.py", line 53, in new_mongo_collection
    raise e
  File "/app/storage/storage.py", line 51, in new_mongo_collection
    db.create_collection(name)
  File "/usr/local/lib/python3.6/dist-packages/pymongo/database.py", line 407, in create_collection
    raise CollectionInvalid("collection %s already exists" % name)
pymongo.errors.CollectionInvalid: collection example_app_entity already exists`
**Environment details**
- Docker info
- Phantoscope version (v0.2.0)

**Comment by ABNER-1** [comment]
It seems that this application mongo collection already exists.
If you first run it, you can clear all your mongo and milvus data and rerun the quickstart.
```bash
# delete all data before
docker-compose down
rm -rf /mnt/ps
```
Or you can change application name in the script and have a retry.

Of course, this problem may be caused by a previous problem. However, from your error log, I advised that clear your environment and retry it for more details information.

Thanks for watching phantoscope.

**Comment by wq1315** [comment]
Thanks for the quick reply.I tried it again according to your method, and then the following error appeared.
`
Endpoint:  http://172.19.0.2:9000  http://127.0.0.1:9000

Browser Access:
   http://172.19.0.2:9000  http://127.0.0.1:9000

Object API (Amazon S3 compatible):
   Go:         https://docs.min.io/docs/golang-client-quickstart-guide
   Java:       https://docs.min.io/docs/java-client-quickstart-guide
   Python:     https://docs.min.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide
Detected default credentials 'minioadmin:minioadmin', please change the credentials immediately using 'MINIO_ACCESS_KEY' and 'MINIO_SECRET_KEY'
`
Is my setting wrong for this situation?

**Comment by ABNER-1** [comment]
I can not understand your information paste before.
Is minio error?
This is minio reported warning to access web. However, is it confused with your phantoscope running?

**Comment by wq1315** [comment]
Yes, when I create the application, it will report this error.
`{"message": "There was some error when create s3 buckets", "error": "S3Error"}`

**Comment by ABNER-1** [comment]
You should set environment by
`export LOCAL_ADDRESS=$(ip a | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1'| head -n 1)`
before `docker compose up`

If not, you should restart it by
```bash
export LOCAL_ADDRESS=$(ip a | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1'| head -n 1)
docker-compose down
docker-compose up -d
```
then, retry the command to create application.
Have a good luck!

**Comment by ABNER-1** [comment]
Close because alreadey find the problem with cloud firewall.
