### ISSUE TITLE
pipeline creation error: 500 Internal Server Error

### ISSUE THREAD

**Issue by sunyun0090** [zilliztech/phantoscope#157]
**What is your question?**
![image](https://user-images.githubusercontent.com/14146919/91114669-05467d80-e6bb-11ea-99ed-f5cedf52c053.png)
![image](https://user-images.githubusercontent.com/14146919/91114682-0b3c5e80-e6bb-11ea-93ba-6277dafed590.png)
![image](https://user-images.githubusercontent.com/14146919/91114691-10011280-e6bb-11ea-8047-f89fbabb31c2.png)

**Comment by sunyun0090** [comment]
here is the docker log:
![image](https://user-images.githubusercontent.com/14146919/91115509-f660ca80-e6bc-11ea-9df9-c90a82dc650a.png)

**Comment by sunyun0090** [comment]
here is the docker log:
![image](https://user-images.githubusercontent.com/14146919/91116134-41c7a880-e6be-11ea-8408-0b19b39f9d34.png)
![image](https://user-images.githubusercontent.com/14146919/91116141-49874d00-e6be-11ea-9d23-a0f70cc51b77.png)

**Comment by ABNER-1** [comment]
What's your phantoscope version and os information.
It looks like phantoscope can not connect to operator instance. 
Can you get container `api-server  detector1 encoder1` ip?

**Comment by sunyun0090** [comment]
![image](https://user-images.githubusercontent.com/14146919/91117285-d0d5c000-e6c0-11ea-82b1-0fea698fbca0.png)
![image](https://user-images.githubusercontent.com/14146919/91117288-d3d0b080-e6c0-11ea-892c-f60b54d2a125.png)
it seems that face_detector1 has sth wrong

**Comment by ABNER-1** [comment]
No, it's all right.

Can you get you api-server container ip?

What's your os information and phantoscope version ?

**Comment by sunyun0090** [comment]
phantoscope version: 0.2.0
 os information: Linux version 3.10.0-1127.13.1.el7.x86_64
api-server container ip: 172.26.190.79(private)

**Comment by ABNER-1** [comment]
It seems api-server and operator instance do not exist in the same network.
Could you show me  `docker inspect <one of operator instance docker id>` `Networks` fields?

**Comment by sunyun0090** [comment]
face_detector1:
"Networks": {
                "phantoscope_default": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "8aba6e786d67"
                    ],
                    "NetworkID": "c49302d059521d6eb8e6fbcea76bbfbdadf6a770e2d2ceb16bb3f99868cb37a3",
                    "EndpointID": "ca32f425338371fedb7af68d278c0dd7dff6de0f7c627ce29b0f8524f7ff2900",
                    "Gateway": "172.18.0.1",
                    "IPAddress": "172.18.0.8",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:12:00:08",
                    "DriverOpts": null
                }
            }
api-server:
"Networks": {
                "phantoscope_default": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "api",
                        "670344051e89"
                    ],
                    "NetworkID": "c49302d059521d6eb8e6fbcea76bbfbdadf6a770e2d2ceb16bb3f99868cb37a3",
                    "EndpointID": "176264669d2c536c9f213db5bdfd54cece5f2e41813d793182e9771d15d1929e",
                    "Gateway": "172.18.0.1",
                    "IPAddress": "172.18.0.5",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:12:00:05",
                    "DriverOpts": null
                }
            }

**Comment by ABNER-1** [comment]
All right here. 
Api-server and operator instances are in the same network.
It's confusing.

I suggest that you can retry it.
Of course, you can docker exec into the api-server and ping the ip of detector1 and encoder1 container to ensure the communication between them not refused by firewall.

**Comment by sunyun0090** [comment]
I've cleared the environment and repeated all the steps.  I've created example_app and object_example successfully.
but when i run the following script , the API still return info  ' 500 Internal Server Error'.
Can you help me find the script problem?

`export LOCAL_ADDRESS=$(ip a | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1'| head -n 1)


curl --location --request POST ${LOCAL_ADDRESS}':5000/v1/operator/register' \
--header 'Content-Type: application/json' \
--data '{
    "name": "face_detector",
    "addr": "psoperator/face-detector:latest",
    "author" :"phantoscope",
    "type":"processor",
    "description": "detect face in input images",
    "version": "0.1.0"
}'


curl --location --request POST ${LOCAL_ADDRESS}':5000/v1/operator/register' \
--header 'Content-Type: application/json' \
--data '{
    "name": "face_encoder",
    "addr": "psoperator/face-encoder:latest",
    "author" :"phantoscope",
    "type":"encoder",
    "description": "embedding face img as vector",
    "version": "0.1.0"
}'

 curl --location --request POST ${LOCAL_ADDRESS}':5000/v1/operator/face_detector/instances/face_detector1' \
--header 'Content-Type: application/json'


 curl --location --request POST ${LOCAL_ADDRESS}':5000/v1/operator/face_encoder/instances/face_encoder1' \
--header 'Content-Type: application/json'

  


# 下面这步一直错误
curl --location --request POST ${LOCAL_ADDRESS}':5000/v1/pipeline/face_pipeline' \
--header 'Content-Type: application/json' \
--data '{
	"description":"face img detect and encode",
	"processors": [{
		"name": "face_detector",
		"instance":"face_detector1"
	}],
	"encoder": {
		"name": "face_encoder",
		"instance":"face_encoder1"
	}
}'`

**Comment by ABNER-1** [comment]
I have found  a bug of these two operator.
I will fix it today.

**Comment by ABNER-1** [comment]
I have fix operator image bug. 
you should run `docker ps -a | grep phantoscope_ | awk '{print $1}' | xargs docker rm -f` delete wrong instance
run `docker rmi psoperator/face-detector:latest` and `docker rmi psoperator/face-encoder:latest` to delete previous docker images.
Then you could pull new image by yourself or create instances directly.

Thanks for your issue report.

**Comment by sunyun0090** [comment]
it's ok. thank you !
