### ISSUE TITLE
Create Operator Instance Failure

### ISSUE THREAD

**Issue by heshuai64** [zilliztech/phantoscope#177]
**What is your question?**
Create Operator Instance 
curl -X POST "http://127.0.0.1:5000/v1/operator/ssd_detector/instances/ssd_instance1" -H  "accept: application/json" -d ""
Return Info：messageerror%

OS version: Mac OS 10.15.7
docker desktop version:  2.4.2.0

**Comment by ABNER-1** [comment]
Can you run command `docker image |grep ssd` to ensure whether image of ssd had been pulled.
If not, maybe your error was caused by the network.
Maybe pulling image of ssd operator manually help.
