### ISSUE TITLE
Is there a size limit for images when I am using curl to import ?

### ISSUE THREAD

**Issue by chencong-hakka** [zilliztech/phantoscope#178]
Hello, Is there a size limit for images when I am using curl to import ?
if I upload a 800*800 image ：
{"message": "Unexpected error happen when upload: (\"can't encode data by encoder, check input or encoder\", '')", "error": "UnexpectedError"}
if i compress the image to 400*400 : success。

**Comment by ABNER-1** [comment]
I think this is not a limit with image size.
Maybe this happens because your image can not be detected when input is 800 * 800. 

However, this is just my suppose. 
If you need help, you should give me more information about your version \ your pipeline and  your application information.
Of course, the error input image pasted also weclome.

**Comment by chencong-hakka** [comment]
OS：ubuntu 18.04
phantoscope version : 0.2.0
pipeline:
`{
    "name": "object_pipeline",
    "input": null,
    "output": null,
    "processors": [
        {
            "operator": {
                "name": "ssd_detector",
                "addr": "psoperator/ssd-detector:latest",
                "author": "phantoscope",
                "version": "0.1.0",
                "type": "processor",
                "description": "detect object in input images",
                "runtime_client": "docker",
                "metadata": {
                    "id": "eb253ae8-023d-4c42-9c6c-3821af656b1b",
                    "create_time": "2020-11-26 06:53:36.828258",
                    "resource_type": "Operator",
                    "state": "created"
                }
            },
            "instance": {
                "id": "9a128f1094",
                "name": "phantoscope_ssd_detector_ssd_instance1",
                "status": "running",
                "ports": {
                    "80/tcp": [
                        {
                            "HostIp": "0.0.0.0",
                            "HostPort": "32769"
                        }
                    ]
                },
                "ip": "172.18.0.6",
                "endpoint": "172.18.0.6:80"
            }
        }
    ],
    "encoder": {
        "operator": {
            "name": "xception_encoder",
            "addr": "psoperator/xception-encoder:latest",
            "author": "phantoscope",
            "version": "0.1.0",
            "type": "encoder",
            "description": "embedding picture as vector",
            "runtime_client": "docker",
            "metadata": {
                "id": "ff63348e-6859-4be4-bf05-272cd9b39df0",
                "create_time": "2020-11-26 06:54:17.751743",
                "resource_type": "Operator",
                "state": "created"
            }
        },
        "instance": {
            "id": "93a2844195",
            "name": "phantoscope_xception_encoder_xception_instance1",
            "status": "running",
            "ports": {
                "80/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "32770"
                    }
                ]
            },
            "ip": "172.18.0.7",
            "endpoint": "172.18.0.7:80"
        }
    },
    "description": "object detect and encode",
    "metadata": {
        "id": "3301acb0-fa6f-4dbe-b6dc-f0f82f4d7375",
        "create_time": "2020-11-26 06:59:51.152493",
        "resource_type": "Pipeline",
        "state": "created"
    }
}`

application:
`{
    "name": "object_example",
    "fields": {
        "object_field": {
            "type": "pipeline",
            "value": "object_pipeline"
        }
    },
    "bucket": "object-s3",
    "metadata": {
        "id": "e771b42b-35ef-4e8c-b9a0-4aae45328553",
        "create_time": "2020-11-26 07:00:46.857812",
        "resource_type": "Application",
        "state": "created"
    }
}`

images:
http://img.ruitulight.com/image_er503_1605860976463.jpg
https://img.deng51.com/o_1ei7n9or588v18eu110pdti1iqa2d.png
https://img.deng51.com/o_1ei7n9shoc6m1bgu1h8iu3m183k2i.png

Thank you

**Comment by chencong-hakka** [comment]
> I think this is not a limit with image size.
> Maybe this happens because your image can not be detected when input is 800 * 800.
> 
> However, this is just my suppose.
> If you need help, you should give me more information about your version \ your pipeline and your application information.
> Of course, the error input image pasted also weclome.



OS：ubuntu 18.04
phantoscope version : 0.2.0
pipeline:
`{ "name": "object_pipeline", "input": null, "output": null, "processors": [ { "operator": { "name": "ssd_detector", "addr": "psoperator/ssd-detector:latest", "author": "phantoscope", "version": "0.1.0", "type": "processor", "description": "detect object in input images", "runtime_client": "docker", "metadata": { "id": "eb253ae8-023d-4c42-9c6c-3821af656b1b", "create_time": "2020-11-26 06:53:36.828258", "resource_type": "Operator", "state": "created" } }, "instance": { "id": "9a128f1094", "name": "phantoscope_ssd_detector_ssd_instance1", "status": "running", "ports": { "80/tcp": [ { "HostIp": "0.0.0.0", "HostPort": "32769" } ] }, "ip": "172.18.0.6", "endpoint": "172.18.0.6:80" } } ], "encoder": { "operator": { "name": "xception_encoder", "addr": "psoperator/xception-encoder:latest", "author": "phantoscope", "version": "0.1.0", "type": "encoder", "description": "embedding picture as vector", "runtime_client": "docker", "metadata": { "id": "ff63348e-6859-4be4-bf05-272cd9b39df0", "create_time": "2020-11-26 06:54:17.751743", "resource_type": "Operator", "state": "created" } }, "instance": { "id": "93a2844195", "name": "phantoscope_xception_encoder_xception_instance1", "status": "running", "ports": { "80/tcp": [ { "HostIp": "0.0.0.0", "HostPort": "32770" } ] }, "ip": "172.18.0.7", "endpoint": "172.18.0.7:80" } }, "description": "object detect and encode", "metadata": { "id": "3301acb0-fa6f-4dbe-b6dc-f0f82f4d7375", "create_time": "2020-11-26 06:59:51.152493", "resource_type": "Pipeline", "state": "created" } }`

application:
`{ "name": "object_example", "fields": { "object_field": { "type": "pipeline", "value": "object_pipeline" } }, "bucket": "object-s3", "metadata": { "id": "e771b42b-35ef-4e8c-b9a0-4aae45328553", "create_time": "2020-11-26 07:00:46.857812", "resource_type": "Application", "state": "created" } }`

images:
http://img.ruitulight.com/image_er503_1605860976463.jpg
https://img.deng51.com/o_1ei7n9or588v18eu110pdti1iqa2d.png
https://img.deng51.com/o_1ei7n9shoc6m1bgu1h8iu3m183k2i.png

Thank you

**Comment by ABNER-1** [comment]
Hello @chencong-hakka .
Your pipeline contains a detector, and you will get this error if detect no result by pipeline.

You could read the detector logs to verify this suppose.

About this result that you got result with 400 * 400 input but none with 800 * 800, I can't explain how it did. 
However it is indeed the normal result judged by ssd detector. If you want to imporve its detect precision, you could change its threshod or fine-tune it.

**Comment by chencong-hakka** [comment]
> Hello @chencong-hakka .
> Your pipeline contains a detector, and you will get this error if detect no result by pipeline.
> 
> You could read the detector logs to verify this suppose.
> 
> About this result that you got result with 400 * 400 input but none with 800 * 800, I can't explain how it did.
> However it is indeed the normal result judged by ssd detector. If you want to imporve its detect precision, you could change its threshod or fine-tune it.

Thank you
