### ISSUE TITLE
face distances seem inaccuracy 

### ISSUE THREAD

**Issue by sunyun0090** [zilliztech/phantoscope#179]
http://117.132.2.109:8888/group1/M00/00/05/wKgTCWACSv6AL4XJAACpmRR-3cg197.jpg
http://117.132.2.109:8888/group1/M00/00/0B/wKgTCWACTj6ASfCIAABnC3vLURE399.jpg

these L2 distance of above two pictures is about 0.4.
but, the similar result of baidu is about 35%.

what can i do to improve accuracy?
thank you!

**Comment by ABNER-1** [comment]
1. Why do you want to get a result similar with baidu search result?
2. What's your AI model for emebedding?

I can't understand why you need  to do this job.
However, I think this may be not a phantoscope accuracy question.
