### ISSUE TITLE
Question about ssd operator implementation? 

### ISSUE THREAD

**Issue by liyuxuan89** [zilliztech/phantoscope#181]
def Execute(self, request, context):
        logging.info("execute")
        grpc_metas = []
        result_images = run(self.detector, request.datas, request.urls)
        # just for test, need adjust proto
        logging.info('len of result images： %d', len(result_images))
        result_images = result_images[0]

        for result_image in result_images:
            data = rpc.rpc_pb2.MetaData(data=bytes(result_image, encoding='utf-8'))
            grpc_metas.append(data)
        return rpc.rpc_pb2.ExecuteReply(nums=len(grpc_metas),
                                        vectors=[],
                                        `metadata=grpc_metas)`
What do you mean by “just for test”？
result_images = result_images[0] , Does that mean the operator will only process one image at a time ?

**Comment by ABNER-1** [comment]
Yes, you're right.
This is just a solution in current version because of the design of rpc proto.
